# Generated by Django 5.1.5 on 2025-02-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prepation_steps',
            new_name='preparation_steps',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prepation_steps_is_html',
            new_name='preparation_steps_is_html',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prepation_time',
            new_name='preparation_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prepation_time_unit',
            new_name='preparation_time_unit',
        ),
    ]
